[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bson>=0.5.10",
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "pymongo>=4.11.3",
    "python-dotenv>=1.0.1",
]
